version: '3.8'
services:
  api:
    build: .
    container_name: nusarithm-api
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - TRANSFORMERS_CACHE=/app/cache
    volumes:
      - ./app:/app/app
      - ./cache:/app/cache
